### ISSUE TITLE
fetch not working with localhost.

### ISSUE THREAD

**Issue by zendevil** [superstructor/re-frame-fetch-fx#1]
When I try the following in my re-frame :fetch map:

```
{:method :get 
:url "https://google.com"
:params some-params
:response-content-types {#"application/.*json" :json}
:on-success print-response
:on-failure show-failure
}

```

the on-success function is run on the "https://google.com" but the on-failure function is run when I try a localhost:3000/some-route route. I know that the route works because it works when directly put into the browser. The route is supposed to return a json.

**Comment by superstructor** [comment]
The issue your having is [CORS blocks different origins by default](https://github.com/superstructor/re-frame-fetch-fx#cross-origin-resource-sharing-cors). This is the same as the underlying `js/fetch` API. Please set appropriate `:mode` as per [examples](https://github.com/superstructor/re-frame-fetch-fx#comprehensive-example). I also added a unit test that passes for this case.
